apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uwqy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uwqy
    app.kubernetes.io/part-of: ci10t-786-0095-app
  name: devfile-sample-uwqy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uwqy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uwqy
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0095-tenant/ci10t-786-0095-app/devfile-sample-uwqy@sha256:5d81dbb086380408d2069d1034866709eca704003b47b050bd9ce420b393c87d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
